findLocationAttempts: 50
enableEventScheduler: true
placeholders:
  dropNotActive: "Не активен!"
  dropIsActive: "Активен!"
  eventPoolIsEmpty: "Пусто!"
  isNext: "Следующий"
  isNotNext: "Не следующий"
  locationIsNull: "---"
messages:
  eventPoolIsEmpty: "{SP} Доступных ивентов не было найдено!"
  reload: '{SP} Вы успешно перезагрузили плагин!'
  eventIsInactive: '{SP} Ивент [id] еще не активен!'
  eventsAreInactive: "{SP} Сейчас не запущено ни одного ивента!"
  eventIsActive: '{SP} Ивент [name] уже активен!'
  eventNotExists: '{E}{SPR} Ивента {E}[id] &fне существует!'
  delayNext:
    global:
      - ' '
      - '{SP} Следующий ивент: [name]'
      - '{SP} Время призыва: [next_time]'
      - ' '
    taped:
      - ' '
      - '{SP} Ивент [name] &fбудет в {S}[next_time]'
      - ' '
  teleport: '{SP} Вы телепортировались к ивенту {S}%event_now_name%'
  locate:
    - ' '
    - '[RUNCOMMAND] {SP} Координаты ивента [name]: *%*{S}[ [x]; [y]; [z] ]*%*/event tp [id]*%*'
    - '{SP} Мир локации ивента: {S}[world]'
    - ' '
  compass: '{L}{SPR} Вы успешно установили стрелку компаса на {L}ивент!'
  noCompass: '{E}{SPR} Возьмите для начала в руку компас!'
  start: '{SP} Вы успешно запустили ивент {S}[name]'
  stop: '{SP} Вы успешно остановили ивент [name]!'
  stopAll: '{SP} Вы успешно остановили все ивенты!'