findLocationAttempts: 20
messages:
  dropNotActive: "Не активен!"
  dropIsActive: "Активен!"
  reload: '{SP} Вы успешно перезагрузили плагин!'
  inactive: '{SP} Ивент еще не активен!'
  isActive: '{SP} Ивент уже активен!'
  notExists: '{E}{SPR} Ивента {E}[event_name] &fне существует!'
  delayNext:
    - ' '
    - '{SP} Следующий ивент будет в {S}%event_next_time[a]%'
    - ' '
  delay:
    - ' '
    - '{SP} Ивент [event_name] &fбудет в {S}[event_time_left]'
    - ' '
  teleport: '{SP} Вы телепортировались к ивенту {S}%event_now_name%'
  locate:
    - ' '
    - '[RUNCOMMAND] {SP} Координаты ивента: *%*{S}[ %event_x%; %event_y%; %event_z% ]*%*/event tp*%*'
    - '{SP} Мир локации ивента: {S}%lunaspring_localize-worlds.{event_world}%'
    - ' '
  compass: '{L}{SPR} Вы успешно установили стрелку компаса на {L}ивент!'
  noCompass: '{E}{SPR} Возьмите для начала в руку компас!'
  startRandom: '{E}{SPR} Вы успешно запустили рандомный ивент!'
  start: '{SP} Вы успешно запустили ивент {S}[event_name]'
  stop: '{SP} Вы успешно остановили ивент!'