# findLocationAttempts - максимальное кол-во попыток для нахождения рандомной локации генератором RandomSpawnSettings
# Если кол-во попыток перевалило за это число, то локация станет null и ивент не будет заспавнен
# При этом, если оставить это число большим, то это может вызвать лаги, в основном это ограничитель против бесконечного поиска
findLocationAttempts: 50
# enableEventScheduler - параметр, отвечающий за включение планировщика, который управляет сразу всеми
# Событиями сервера для их призыва в нужное время. Отключите параметр если все ивенты на сервере реализуют свой планировщик
enableEventScheduler: true
placeholders:
  dropNotActive: "Не активен!"
  dropIsActive: "Активен!"
  eventPoolIsEmpty: "Пусто!"
  isNext: "Следующий"
  isNotNext: "Не следующий"
  locationIsNull: "---"
messages:
  nextStage: "{SP} Вы успешно пропустили этап ивента [name]! &7([prevStageName])"
  nextStageError: "{SPE} Этот этап &7([stageName])&f ивента [name]&f помечен как обязательный!"
  actionThrows: "{SPE} Упс. Во время выполнения произошла ошибка: {E}[exception]"
  eventPoolIsEmpty: "{SPE} Доступных ивентов не было найдено!"
  reload: '{SP} Вы успешно перезагрузили плагин!'
  eventIsInactive: '{SPE} Ивент [id] еще не активен!'
  eventsAreInactive: "{SPE} Сейчас не запущено ни одного ивента!"
  eventIsActive: '{SPE} Ивент [name] уже активен!'
  eventNotExists: '{SPE} Ивента {E}[id] &fне существует!'
  delayNext:
    global:
      - ' '
      - '{SP} Следующий ивент: [name]'
      - '{SP} Время призыва через [nextTime]'
      - ' '
    taped:
      - ' '
      - '{SP} Ивент [name] &fбудет через {S}[nextTime]'
      - ' '
  teleport: '{SP} Вы телепортировались к ивенту {S}[activeName]'
  locate:
    - ' '
    - '[RUNCOMMAND] {SP} Координаты ивента [name]: *%*{S}[ [x]; [y]; [z] ]*%*/event tp [id]*%*'
    - '{SP} Мир локации ивента: {S}[world]'
    - ' '
  compass: '{L}{SPR} Вы успешно установили стрелку компаса на {L}ивент!'
  noCompass: '{SPE} Возьмите для начала в руку компас!'
  start: '{SP} Вы успешно запустили ивент {S}[name]'
  stop: '{SP} Вы успешно остановили ивент [name]!'
  stopAll: '{SP} Вы успешно остановили все ивенты!'